jenkinsci/accurev-plugin

src/main/java/hudson/plugins/accurev/AccurevSCM.java

I noticed that no other jobs where being polled when one was already running.
This was caused by the fact that the poll action for one of the jobs could not acquire a workspace because the build was in progress.
Unfortunately `AbstractProject` does not tell you which project it wants to poll when it calls `requiresWorkspaceForPolling()`.
I've added a workaround by using an `SCMPollListener` that stores the instance of the `AbstractProject`, so I can skip polling in `requiresWorkspaceForPolling()` and `compareRemoteRevisionWith()` when a build is in progress.

Added workaround to be able to skip a poll when the build is busy.

---

.gitignore
src/main/java/hudson/plugins/accurev/AccurevLauncher.java
src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/java/hudson/plugins/accurev/DetermineRemoteHostname.java
src/main/java/hudson/plugins/accurev/cmd/ChangeLogCmd.java
src/main/java/hudson/plugins/accurev/cmd/PopulateCmd.java
src/main/java/hudson/plugins/accurev/cmd/Update.java
src/main/java/hudson/plugins/accurev/delegates/AbstractModeDelegate.java
src/main/java/hudson/plugins/accurev/parsers/xml/ParseHistory.java
src/main/resources/hudson/plugins/accurev/AccurevSCM/global.jelly
src/main/webapp/help/use-color.html

Handle some of the NullPointers but I should look into some of the causes.
streamColor is one of those causes without admin privileges you get null pointer.
When HostName is returned as IP, it also gives null pointer.
I would like to have streamColor as a toggle either per job or per server, need to figure that one out.

NullPointer fixes. better hostname handling. Toggle streamColor.

---

src/main/java/hudson/plugins/accurev/AccurevLauncher.java
src/main/java/hudson/plugins/accurev/ParseChangeLog.java

Also removed a bit of duplicate code...

XML parser handles encoding.

---

src/main/java/hudson/plugins/accurev/cmd/Login.java
src/main/java/hudson/plugins/accurev/parsers/xml/ParseGetConfig.java
src/main/java/hudson/plugins/jetty/security/Password.java

Empty password is not fixed for unix 👎

Fix empty password

---

src/main/java/hudson/plugins/accurev/AccurevSCM.java

Possible NPE when servers is null.

---

src/main/java/hudson/plugins/accurev/CheckForChanges.java

Refactored some code in CheckForChanges and tried to sanitize the paths ( #JENKINS-41018 ).
https://issues.jenkins-ci.org/browse/JENKINS-41018

Fixed CheckForChanges (should fix #JENKINS-41018)

---

src/main/java/hudson/plugins/accurev/delegates/WorkspaceDelegate.java

This is a old bug, that was never caught :-1:

[fix/JENKINS-43657] Workspace never returned polling stream

---

pom.xml
src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/java/hudson/plugins/accurev/delegates/AbstractModeDelegate.java
src/main/java/hudson/plugins/accurev/delegates/ReftreeDelegate.java
src/main/java/hudson/plugins/accurev/delegates/WorkspaceDelegate.java
src/test/java/hudson/plugins/accurev/AccurevSCMTest.java

[JENKINS-26100](https://issues.jenkins-ci.org/browse/JENKINS-26100)
Downstream of:
https://github.com/jenkinsci/jenkins/pull/2730

[JENKINS-26100] Change buildEnvVars to take Run

---

pom.xml
src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/java/hudson/plugins/accurev/ParseChangeLog.java
src/main/java/hudson/plugins/accurev/cmd/FilesCmd.java
src/main/java/hudson/plugins/accurev/cmd/GetAccuRevVersion.java
src/main/java/hudson/plugins/accurev/cmd/PopulateCmd.java
src/main/java/hudson/plugins/accurev/delegates/AbstractModeDelegate.java
src/main/java/hudson/plugins/accurev/parsers/xml/ParseHistory.java
src/main/java/hudson/plugins/accurev/parsers/xml/ParseUpdate.java
src/main/kotlin/hudson/plugins/accurev/AccurevElement.kt
src/main/kotlin/hudson/plugins/accurev/AccurevUtils.kt
src/main/kotlin/hudson/plugins/accurev/parsers/xml/ParseFiles.kt
src/main/webapp/help/project/stream.html

[JENKINS-44748](https://issues.jenkins-ci.org/browse/JENKINS-44748)

[JENKINS-44748] Ensure defunct files are removed from populating files

---

src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/resources/hudson/plugins/accurev/AccurevSCM/AccurevServer/config.groovy

This is the COULD-HAVE  requested by customer.

Request for Jenkins plug-in to have "Validate" button to test connection/login

---

src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/java/hudson/plugins/accurev/cmd/PopulateCmd.java
src/main/resources/hudson/plugins/accurev/AccurevSCM/config.jelly
src/main/webapp/help/project/subpathonly.html

Utilizes the "-D" option of the pop command

Add option to populate the sub-path only, without creating the directory tree

---

src/main/webapp/help/project/subpath.html

I have just updated a help document for SubPath.html in this PR.
Added example with "*" to pick changes in sub-directories while polling.
please review and merge.

Update help message for sub path

---

.github/workflows/maven.yml

As ci.jenkins.io is having a off day 😓

Add GitHub Action CI

---

Jenkinsfile
pom.xml

remove spotbugs profile, which is now included in parent pom

bump parent pom, bump jenkins patch version, use bom dependency management

---

src/main/java/hudson/plugins/accurev/AccurevLauncher.java

Updated the changes for avoiding multiple session creation in .jenkins directory.

Updated the changes for avoiding multiple session creation

---

src/main/java/hudson/plugins/accurev/AccurevLauncher.java
src/main/java/hudson/plugins/accurev/CheckForChanges.java
src/main/java/hudson/plugins/accurev/ParseChangeLog.java
src/main/java/hudson/plugins/accurev/cmd/PopulateCmd.java
src/main/java/hudson/plugins/accurev/delegates/ReftreeDelegate.java
src/main/java/hudson/plugins/accurev/delegates/SnapshotDelegate.java
src/main/java/hudson/plugins/accurev/delegates/StreamDelegate.java
src/main/java/hudson/plugins/accurev/delegates/WorkspaceDelegate.java
src/main/java/hudson/plugins/accurev/parsers/xml/ParseHistory.java
src/main/resources/hudson/plugins/accurev/AccurevChangeLogSet/digest.jelly
src/main/resources/hudson/plugins/accurev/AccurevChangeLogSet/index.jelly
src/main/webapp/help/project/filterforpollscm.html

Updated the changes for subpath related fixes

Updated the changes for subpath related fixes

---

src/main/resources/index.jelly

Made the text blurb on the 'manage plugin' page more informative and URL point to the company product page.

Update plugin blurb and URL

---

src/main/java/hudson/plugins/accurev/delegates/AbstractModeDelegate.java

Added check for `changeLogFile != null` as is the case when a user selects `changelog:false`

Closing issue #96

---

pom.xml

Reverts jenkinsci/accurev-plugin#109

Revert "Fix antrun version"

---

pom.xml

Removing java level from pom.xml
```[tasklist]
```

removing java level from pom

---

pom.xml
src/main/java/hudson/plugins/accurev/AccurevChangeLogSet.java
src/main/java/hudson/plugins/accurev/AccurevLauncher.java
src/main/java/hudson/plugins/accurev/AccurevReferenceTree.java
src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/main/java/hudson/plugins/accurev/AccurevTransaction.java
src/main/java/hudson/plugins/accurev/AccurevWorkspace.java
src/main/java/hudson/plugins/accurev/CheckForChanges.java
src/main/java/hudson/plugins/accurev/DetermineRemoteHostname.java
src/main/java/hudson/plugins/accurev/GetConfigWebURL.java
src/main/java/hudson/plugins/accurev/RefTreeExternalFile.java
src/main/java/hudson/plugins/accurev/RemoteWorkspaceDetails.java
src/main/java/hudson/plugins/accurev/delegates/ReftreeDelegate.java
src/main/java/hudson/plugins/accurev/delegates/WorkspaceDelegate.java
src/main/java/jenkins/plugins/accurev/AccurevTool.java

Increasing spotbugs effort to max and threshold to low.  Also resolving the resulting spotbugs findings.
```[tasklist]
```

Fixing spotbugs findings

---

src/main/java/hudson/plugins/accurev/parsers/xml/ParseHistory.java

Update ParseHistory.java to handle all the 'version' tags in one transaction

---

Jenkinsfile

Add Java JDK 17 and 21 test configurations

---

.github/workflows/maven.yml

Specify java distribution

---

src/main/java/hudson/plugins/accurev/AccurevSCM.java
src/test/java/hudson/plugins/accurev/ConfigurationAsCodeTest.java

Fixed deprecated method calls
